-- 상품 재고와 낙관적 잠금 버전을 저장하는 기본 테이블입니다.
CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    price NUMERIC(19, 2) NOT NULL,
    stock INTEGER NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ck_products_price_positive CHECK (price > 0),
    CONSTRAINT ck_products_stock_non_negative CHECK (stock >= 0)
);

-- 주문, 결제 상태, 멱등성 키와 추적 가능한 시각 정보를 저장합니다.
CREATE TABLE purchase_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idempotency_key VARCHAR(64) NOT NULL,
    user_id VARCHAR(64) NOT NULL,
    product_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL,
    total_price NUMERIC(19, 2) NOT NULL,
    status VARCHAR(30) NOT NULL,
    transaction_id VARCHAR(100),
    failure_reason VARCHAR(300),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_purchase_orders_idempotency_key UNIQUE (idempotency_key),
    CONSTRAINT ck_purchase_orders_quantity CHECK (quantity BETWEEN 1 AND 100),
    CONSTRAINT ck_purchase_orders_total_price CHECK (total_price > 0),
    CONSTRAINT ck_purchase_orders_status CHECK (
        status IN ('PENDING', 'PAYMENT_PROCESSING', 'PAID', 'PAYMENT_DECLINED', 'PAYMENT_UNKNOWN')
    ),
    CONSTRAINT fk_purchase_orders_product FOREIGN KEY (product_id) REFERENCES products(id)
);

CREATE INDEX idx_purchase_orders_user_created
    ON purchase_orders (user_id, created_at);
